---
title: "Homework 5"
author: "Harsha Senapathi"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(patchwork)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )


options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
set.seed(1)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

### Problem 1
```{r}
fill_data = function(x) {
  if (is.numeric(x)) {
    replace_na(x, mean(x, na.rm = TRUE))
  } else if (is.character(x)) {
    replace_na(x, "virginica")
  }
}

iris = map_df(iris_with_missing, fill_data)
```

### Problem 2

```{r}
path = str_c("./data/", list.files("./data/")) 
file_name = list.files("./data/")

vec_file_name = 
  tibble( 
    path = path[1:20], 
    file_name = file_name[1:20]
)

pcpt_data_tidy =
  purrr::map_df(vec_file_name$path, read_csv) %>% 
  unnest() %>% 
  cbind(file_name = vec_file_name$file_name) %>% 
  separate(file_name, into = c("arm", "id"), sep = "_") %>% 
  separate(id, into = c("id_num", "remove"), sep = 2) %>% 
  pivot_longer(week_1:week_8,
    names_to = "week",
    values_to = "obsv",
    names_prefix = "week_"
  ) %>% 
 select(arm, id_num, week, obsv)


pcpt_data_tidy %>% 
  ungroup() %>% 
  mutate(arm_id = paste(arm, id_num, sep = "_")) %>% 
  ggplot(aes(x = week, y = obsv, color = arm, group = arm_id)) +
    geom_line() +
    labs(
      title = "Observations on each subject over time",
      x = "Week Number",
      y = "Observation",
      color = 'Arm'
    ) 
```

Problem 3

```{r}

regression = function(beta1 = 0) {
  
  sim_regression = tibble(
    x = rnorm(30, mean = 0, sd = 1),
    y = 2 + beta1 * x + rnorm(30, 0, sd = 50^(1/2))
      )
  
  ls_fit = lm(y ~ x, data = sim_regression)
  
  tibble(
    beta1_hat = broom::tidy(ls_fit)[2, 2] %>% as.numeric(),
    p_value = broom::tidy(ls_fit)[2, 5] %>% as.numeric()
  )
}
```


```{r}
sim_results = tibble(beta_1 = c(0, 1, 2, 3, 4, 5, 6)) %>% 
  mutate(output_lists = map(.x = beta_1, ~rerun(10000, regression(beta1 = .x))),
         estimate_dfs = map(output_lists, bind_rows)) %>%
  select(-output_lists) %>%
  unnest(estimate_dfs)
```

```{r}

sim_results %>% 
  group_by(beta_1) %>%
  count(reject = p_value < 0.05) %>% 
  mutate(percent = n/sum(n)*100) %>% 
  filter(reject == TRUE) %>%
  ggplot(aes(x = beta_1, y = percent)) +
  geom_point() + 
  geom_line()

```

```{r}

p1 = sim_results %>% 
  group_by(beta_1) %>%
  summarise(mean = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta_1, y = mean)) + 
  geom_point() + 
  geom_line()

p2 = sim_results %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta_1) %>%
  summarise(mean = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta_1, y = mean)) + 
  geom_point() +
  geom_line()

```






